### ISSUE TITLE
Plan to train a model on all corpus?

### ISSUE THREAD

**Issue by MrRace** [SVAIGBA/TwASP#3]
1. The published models just been trained on specific corpus, do you plan to train a model on all of corpus including UDs and CTBs?  It seems to lead to a more robust model? 
2. Would you plan to extend the model to NER? It seems logical. As you have validated the model on word segmentation and POS, therefore to further enhance on NER can also been expected.

**Comment by yuanheTian** [comment]
That is a good point!

We plan to do both of them in the future.
